local assert = require("luassert")

local function read(path)
  local fd = assert(io.open(path, "r"))
  local body = fd:read("*a")
  fd:close()
  return body
end

describe("TetraVim.util.quality.profiling", function()
  it("should expose start, stop, and view API methods", function()
    local profiling = require("TetraVim.util.quality.profiling")
    assert.is_table(profiling)
    assert.is_function(profiling.start)
    assert.is_function(profiling.stop)
    assert.is_function(profiling.view)
  end)

  it("should initialize active_pid and last_flamegraph to nil", function()
    local profiling = require("TetraVim.util.quality.profiling")
    assert.is_nil(profiling.active_pid)
    assert.is_nil(profiling.last_flamegraph)
  end)

  it("should expose the interactive call-tree API", function()
    local profiling = require("TetraVim.util.quality.profiling")
    assert.is_function(profiling.pick_pid)
    assert.is_function(profiling.capture)
    assert.is_function(profiling._render_panel)
    assert.is_function(profiling._toggle)
    assert.is_table(profiling._collapsed)
    assert.is_nil(profiling._tree)
  end)

  it("wires <leader>jpp to the interactive capture", function()
    local body = read(vim.fn.getcwd() .. "/lua/TetraVim/util/jvm/jvm.lua")
    assert.is_truthy(body:find("<leader>jpp", 1, true))
    assert.is_truthy(body:find('require("TetraVim.util.quality.profiling").capture()', 1, true))
  end)

  it("has a jps probe in the profiling health section", function()
    local body = require("TetraVim.tests.helpers").health_source()
    assert.is_truthy(body:find("TetraVim JVM Continuous Profiling", 1, true))
    assert.is_truthy(body:find('vim.fn.executable("jps")', 1, true))
  end)
end)
